### ISSUE TITLE
Contour extraction error due to `matplotlib`

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [noaa-ocs-modeling/OCSMesh#144]
Testing by @felicio93 showed an issue with OCSMesh contour extraction when using latest `matplotlib`:

> Downgrading matplotlib alone won't solve the problem due to mpl dependency with the python version.
> 
> I was able to get the right coastline by:
> creating a new env with python 3.9 and then downgrading mpl to 3.5.2
> 
> here is the comparison:
> ![image](https://github.com/noaa-ocs-modeling/OCSMesh/assets/77082694/94b88a04-0fe0-4e03-a262-7c3b2da1f41e)

**Comment by SorooshMani-NOAA** [comment]
@felicio93 this is a good and important item you can look into. I'll assign it to you for now

**Comment by felicio93** [comment]
Ok, I will dig in and try to figure out why this is happening for the latest Matplotlib and Python versions.

**Comment by felicio93** [comment]
I think I found the solution.

The way we are extracting the linestrings no longer works the way it used to.

Long story short, we want a list of lists of coordinates (one list per segment of the coastline). But the recent matplotlib updates were returning all coordinates in a single list, thus connecting vertices that should not be connected.

I just had to change the function _get_raster_contour_single_window in the Raster class to use .allsegs instead of .get_paths()

For the sake of documentation, here are the contour lines for multiple z values iterating over multiple dems:
![image](https://github.com/noaa-ocs-modeling/OCSMesh/assets/61760479/c5d6204d-14e5-4237-aeeb-a9783fc8d2b6)


I will be submitting the PR soon.

**Comment by SorooshMani-NOAA** [comment]
Thanks for looking into this ... make sure you specify the matplotlib version to be bigger than when the new API is added (in case ` .allsegs` didn't exist before a specific version)

**Comment by felicio93** [comment]
good point, let me check that!

**Comment by felicio93** [comment]
Problem solved on the new v1.5.6 OCSMesh version. Closing ticket.
