### ISSUE TITLE
Geometry from polygons

### ISSUE THREAD

**Issue by acroucher** [noaa-ocs-modeling/OCSMesh#31]
I have a DEM in which the elevation values on land are essentially nonsense, so I can't use it to create a geometry by setting a zmax value - because it picks up all kinds of spurious boundaries in the land data.

However I do have a separate shapefile with polygons defining the coastline (high water level). Would it be possible to provide an example showing how to use this to create the geometry? I will also need to be able to define the open sea boundary with a semicircular shape, similar to what is done in the Shinnecock Inlet example in section 9 of the documentation.

**Comment by SorooshMani-NOAA** [comment]
Hi @acroucher, if you already have a shapefile, you can read the shapefile, e.g. using `fiona` (or `geopandas` wrapper to it) and then pass the `shapely` `Polygon` or `MultiPolygon` to the `Geom` factory. Let's say you have a global boundary (ocean side polygon **not** land polygon) shapefile and a circular polygon of region of interest.:
```python
import geopandas as gpd
from shapely.geometry import Point
from ocsmesh import Geom

global_coasts = gpd.read_file('/path/to/global_coasts.shp')
location_of_interest = Point(x, y)
region_of_interest = gpd.GeoDataFrame(
        geomtry=[location_of_interest], crs=roi_crs
    ).buffer(r).to_crs(global_coasts.crs)
simulation_domain = global_coasts.intersection(region_of_interest.unary_union)

geom = Geom(simulation_domain.unary_union , crs=simulation_domain.crs)
``` 
where `x`, `y`, and `r` are the values for the location and the radius of the circular region and `roi_crs` is the CRS in which you'd like to define the region of interset. That would be it for the geometry. 
Note that I'm using `geopandas` for all the CRS transformations and operations so that the example is clearer, you can directly use `pyproj` and `shapely` to generate the final `Polygon` if you'd like.

If you instead have land-side polygon you can replace the `simulation_domain` line with something like this:
```python
simulation_domain = region_of_interest.subtract(global_coasts.unary_union)
```

For the open boundary definition on the final mesh you still need to have a DEM where you can interpolate values, also for getting the autogenerated boundary of mesh the interpolated values from a DEM are used with a threshold. Please let me know if you have any questions I can answer about that stage of meshing.

Please let me know if this answers your question.

**Comment by acroucher** [comment]
Thank you very much, that seems to work very well. It might be worth including an example code snippet like this in the documentation? It seems like something that other people might also want to do.

I may have more questions as I continue to try the software - I was wondering if you think it would be appropriate to enable the 'Discussions' feature on the OCSMesh Github page, so you don't get usage questions like this mixed up with software issues?

**Comment by SorooshMani-NOAA** [comment]
No problem! I agree that having these examples as code snippets would be beneficial to all the users of the package. Unfortunately I haven't had too much time to spend on OCSMesh other than bugfixes and feature additions. 

Also up until recently I and one or two others were the only users, so I really wanted to see use cases from others and slowly build up examples that would be useful to add. So I would really appreciate it if you have other use-cases to discuss here (or preferably in separate tickets)

I will look into enabling "Discussions", if there's no organization-wide policy against it, as this repo is under NOAA managed GitHub organizations.

Since it seem the current issue is resolved, I will mark this ticket as such. But feel free to reopen it if needed, or create other tickets!
