### ISSUE TITLE
Hfun + Mesh: Adding Mesh object inside of collection throws TypeError 

### ISSUE THREAD

**Issue by rjdmartins** [noaa-ocs-modeling/OCSMesh#68]
**Description**
Following the example on page 22 from the documentation, I want to add a Mesh (as well as with other Rasters) to generate a new cleaned-up mesh. Made a simple example where I add only a Mesh inside of collection.
```
from ocsmesh import Hfun, Raster, Mesh, Geom
m = Mesh.open('/_app/mesh_examples/hgrid.ll',crs=4326)
domain = Geom(m).get_multipolygon()
base_gs = gpd.GeoSeries(domain, crs='EPSG:4326')
g=Geom([m],base_shape=base_gs.unary_union, base_shape_crs=base_gs.crs,zmax=0)
h=Hfun([m],base_shape=base_gs.unary_union, base_shape_crs=base_gs.crs,hmin=0,hmax=2000,method='fast')
driver = JigsawDriver(geom=g, hfun=h)
mesh = driver.run()
```

It crashes when creates the HFun: 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ocsmesh/ocsmesh/hfun/hfun.py", line 60, in __new__
    return HfunCollector(hfun, **kwargs)
  File "/ocsmesh/ocsmesh/hfun/collector.py", line 685, in __init__
    self._type_chk(in_list)
  File "/ocsmesh/ocsmesh/hfun/collector.py", line 1364, in _type_chk
    raise TypeError(
TypeError: Input list items must be of type <class 'str'>, <class 'ocsmesh.raster.Raster'>, <class 'ocsmesh.mesh.mesh.Mesh'>, <class 'ocsmesh.hfun.raster.HfunRaster'>, <class 'ocsmesh.hfun.mesh.HfunMesh'>, or a derived type.
```
Checking my m Mesh and it is ocsmesh.mesh.mesh.EuclideanMesh2D type.

I tried also adding Rasters to collection (as in the example), and it is supposed to work, but fails too:
```
m = Mesh.open('/_app/mesh_examples/hgrid.ll',crs=4326)
r = Raster('/_app/raster_examples/gebco/gebco_2022_sub_ice_n90.0_s0.0_w-90.0_e0.0_compressed.tif')
h=Hfun([m,r],base_shape=base_gs.unary_union, base_shape_crs=base_gs.crs,hmin=0,hmax=2000,method='fast')
```
Again, crashes on Hfun:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ocsmesh/ocsmesh/hfun/hfun.py", line 60, in __new__
    return HfunCollector(hfun, **kwargs)
  File "/ocsmesh/ocsmesh/hfun/collector.py", line 685, in __init__
    self._type_chk(in_list)
  File "/ocsmesh/ocsmesh/hfun/collector.py", line 1364, in _type_chk
    raise TypeError(
TypeError: Input list items must be of type <class 'str'>, <class 'ocsmesh.raster.Raster'>, <class 'ocsmesh.mesh.mesh.Mesh'>, <class 'ocsmesh.hfun.raster.HfunRaster'>, <class 'ocsmesh.hfun.mesh.HfunMesh'>, or a derived type.
```
Any idea why does this happens and how can I fix it? 
I'm using OCSMESH 1.1.1, and I'm not sure if this is a bug and was fixed in 1.2.0.

----------------
In the other hand, if instead of adding my Mesh on a collection, I add it as single object, it works.
```
m = Mesh.open('/_app/mesh_examples/hgrid.ll',crs=4326)
h=Hfun(m,base_shape=base_gs.unary_union, base_shape_crs=base_gs.crs,hmin=0,hmax=2000,method='fast')
```

Also I tried to wrap my mesh inside of Hfun and include inside of a Hfun collection. It does not make any sense, but it works. 
```
m = Mesh.open('/_app/mesh_examples/hgrid.ll',crs=4326)
h=Hfun([Hfun(m)],base_shape=base_gs.unary_union, base_shape_crs=base_gs.crs,hmin=0,hmax=2000,method='fast')
g=Geom([m],base_shape=base_gs.unary_union, base_shape_crs=base_gs.crs,zmax=0)
driver = JigsawDriver(geom=g, hfun=h)
mesh = driver.run()
```
The problem is in driver.run(), crashes with Value error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ocsmesh/ocsmesh/driver.py", line 101, in run
    libsaw.jigsaw(
  File "/_venv/lib/python3.8/site-packages/jigsawpy-1.0.0-py3.8.egg/jigsawpy/libsaw.py", line 735, in jigsaw
    raise ValueError(
ValueError: JIGSAW returned code: 6
```

**Versions**
python 3.8.16
OCSMesh 1.1.1 (compiled from source)
shapely 1.8.5
geopandas 0.12.2
pandas 1.5.3
pyarrow 11.0.0
rasterio 1.3.6

**Comment by SorooshMani-NOAA** [comment]
@rjdmartins can you please test [bugfix/hfuntype](https://github.com/noaa-ocs-modeling/OCSMesh/tree/bugfix/hfuntype) branch. It should have the fix for this issue. Please let me know if it works for you.

**Comment by SorooshMani-NOAA** [comment]
> Also I tried to wrap my mesh inside of Hfun and include inside of a Hfun collection. It does not make any sense, but it works.

This is due to the valid type check. `HfunMesh` is accepted as a valid type. Prior to fix in [bugfix/hfuntype](https://github.com/noaa-ocs-modeling/OCSMesh/tree/bugfix/hfuntype), the `EuclideanMesh2D` type was incorrectly rejected as valid, but still `HfunMesh` was accepted. That's the reason it worked when wrapped!

> The problem is in driver.run(), crashes with Value error:

I'll need to look into this one. If I cannot find the cause I'll create a separate ticket for it to track. This is a separate issue from the input type error. Would it be possible for you to share the mesh you're trying to use?

**Update**
Actually I think I know why it's failing. When you provide an `*Mesh*` type, it assumes the values of the mesh are valid size functions. So when you pass either `HfunMesh` or `EuclideanMesh2D` you have to first make sure the values on the mesh are valid for size, e.g. not negative, etc.

**Comment by rjdmartins** [comment]
> @rjdmartins can you please test [bugfix/hfuntype](https://github.com/noaa-ocs-modeling/OCSMesh/tree/bugfix/hfuntype) branch. It should have the fix for this issue. Please let me know if it works for you.

Updated OCSMesh 1.1.1 to 1.2.0 and then switched to that branch to test the fixes. It fixed the Hfun problem.
Tested again the first code, although now crashes in the JIGSAW return code 6.

```
m = Mesh.open('/_app/mesh_examples/hgrid.ll',crs=4326)
domain = Geom(m).get_multipolygon()
base_gs = gpd.GeoSeries(domain, crs='EPSG:4326')
g=Geom([m],base_shape=base_gs.unary_union, base_shape_crs=base_gs.crs,zmax=0)
h=Hfun([m],base_shape=base_gs.unary_union, base_shape_crs=base_gs.crs,hmin=0,hmax=2000,method='fast')
driver = JigsawDriver(geom=g, hfun=h)
mesh = driver.run()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ocsmesh/ocsmesh/driver.py", line 101, in run
    libsaw.jigsaw(
  File "/_venv/lib/python3.8/site-packages/jigsawpy-1.0.0-py3.8.egg/jigsawpy/libsaw.py", line 735, in jigsaw
    raise ValueError(
ValueError: JIGSAW returned code: 6
```

Then I tested for the case of a mesh and raster on collection and worked with no crashes.
```
m = Mesh.open('/_app/mesh_examples/hgrid.ll',crs=4326)
r = Raster('/_app/raster_examples/gebco/gebco_2022_sub_ice_n90.0_s0.0_w-90.0_e0.0_compressed.tif')
h=Hfun([m,r],base_shape=base_gs.unary_union, base_shape_crs=base_gs.crs,hmin=0,hmax=2000,method='fast')
g=Geom([m,r],base_shape=base_gs.unary_union, base_shape_crs=base_gs.crs,zmax=0)
driver = JigsawDriver(geom=g, hfun=h)
mesh = driver.run()
```
Also, I tried to swap the order of the collection  to [r,m] (assuming it could be an issue), and no JIGSAW crash.

> Update
> Actually I think I know why it's failing. When you provide an *Mesh* type, it assumes the values of the mesh are valid size functions. So when you pass either HfunMesh or EuclideanMesh2D you have to first make sure the values on the mesh are valid for size, e.g. not negative, etc.

OK. Checked the .ll file and I can confirm there are some negative values. But if that's the case, the Mesh shouldn't work for both the tests above, right?

Mesh file is here: https://we.tl/t-c0X5Ye6Lpn
The raster is from GEBCO topo sub-ice.

**Comment by SorooshMani-NOAA** [comment]
> It fixed the Hfun problem.

I'm glad the fix worked.

> although now crashes in the JIGSAW return code 6.

Like I said before, this is due to the negative values issue from mesh.

> OK. Checked the .ll file and I can confirm there are some negative values. But if that's the case, the Mesh shouldn't work for both the tests above, right?

In collector size function with `method='fast'`, all the rasters take priority over non-raster inputs, no matter what the input order. So I believe what happens is that the mesh is completely ignored in the final mesh size function, as it is covered by the GEBCO DEM. For `method='fast'` the order of arguments are important **within** each category, e.g. order of rasters and order of mesh inputs separately, but in any case all the rasters have higher priority than all the mesh/hfun inputs. If you want the mesh to take priority, please use `method='exact'`.


In general if you'd like to use a mesh as guide for the mesh size, it's better to first create a "single" size function from it, i.e. `hfun_mesh = Hfun(my_mesh, etc.)` and then call `hfun_mesh.size_from_mesh()`, and after this call pass this `hfun_mesh` as one of the items in the list to the collector constructor, .e.g `hfun_coll = Hfun([raster1, raster2, ..., hfun_mesh], etc.)`.
