### ISSUE TITLE
Enforcing max mesh size

### ISSUE THREAD

**Issue by TPCollings** [noaa-ocs-modeling/OCSMesh#74]
Hi there,

Is there any way to enforce the max mesh size is used on the open boundary? I'm having trouble with instabilities in meshes due to small element sizes being close to the open boundary. The small elements are created by using the sub_tidal_flow_limiter function to delineate the shelf edge. 

I've tried using a polygon containing only the open boundary to along with the add_patch function, but unfortunately the hfun collector always uses the smallest refinement size and therefore the sub_tidal_flow_limiter continues to dominate. Is there anyway to fix the mesh size along the open boundary, so that it isn't refined by the sub_tidal_flow_limiter?

As a work around I was wondering if it's possible to generate two meshes, with one slightly smaller - using the sub_tidal_flow_limiter and another larger one without, and then merging them so you retain a smooth boundary. Is that possible?

Cheers,

Tom

**Comment by SorooshMani-NOAA** [comment]
Hi @TPCollings! I'll try to address what I understand from your description. I think a new feature might be needed (for which I'll create a ticket once I understand the problem).

> Is there any way to enforce the max mesh size is used on the open boundary?

Based on my understanding of the issue, you're trying to enforce the mesh **not** to be smaller than a given size in a specific region. Because the issue is "_... due to small element sizes ..._". So basically you'd like to set a "min" element size to be bigger than a given value locally, regardless of other controls that you applied, such as flow-limiter, right?

> I've tried using a polygon containing only the open boundary to along with the add_patch function...

As you rightly pointed out, all the "refinement" control functions/methods, like `add_patch`, `add_subtidal_flow_limiter`, `add_feature`, etc. compete to set the smallest size for the elements in a given region.

What you need is a what I call a "constraint"  (vs "refinement") for the mesh size. For example, there are `add_topo_bound_constraint` and `add_topo_func_constraint` and `add_courant_num_constraint` that can be used. However, in your case you'd like to have something like a `add_region_constraint` which is not implemented yet.


If that's the case, I can work on adding something like that.

> As a work around I was wondering if it's possible to generate two meshes, with one slightly smaller - using the sub_tidal_flow_limiter and another larger one without, and then merging them so you retain a smooth boundary. Is that possible?

It is possible to generate two meshes and then clip-and-merge them based on a region of interest. See:  https://github.com/noaa-ocs-modeling/OCSMesh/blob/main/ocsmesh/cli/subset_n_combine.py

However it might not be the best solution. **I'd recommend** actually creating two separate size functions, clip them however you want (using `utils.clip_mesh_by_shape`) and then pass them both to a new collector size function. I believe this will be a cleaner solution. Please let me know if you need more information about either of these approaches.

**Comment by TPCollings** [comment]
Hi Soroosh, 

Sorry for the delayed response, we've been off in the UK for a long weekend. 

Yeah, an `add_region_constraint` sounds exactly like what we need. If it would be possible to add a feature like that, then that would be great.

In the meantime I'll try the workaround you've suggested.

Thanks for your help,

Tom

**Comment by TPCollings** [comment]
Hi Soroosh, 

I'm trying to apply the work around you mentioned, but creating two separate size functions and applying them to a new size function collector, but I'm struggling. When you say apply them to a new size function collector, do you mean as mesh, so the code would be something like:

`new_base_hfun  = Hfun([mesh1,mesh2])`

or is there a way to pass exisiting size functions to the Hfun collector? If so, I can't see how to do it.

Cheers,

Tom

**Comment by SorooshMani-NOAA** [comment]
Hi Tom, 

It should work either if you pass them as `HfunRaster` objects or as `HfunMesh` objects. There's one catch though. `HfunCollector` clips the lower priority inputs by the bounding box of the higher priority ones. So (in the extreme case?) if you create two size functions that have the same bounding box, then the second one is fully ignored!

What I had in mind was something like this:
```python
hfun1 = Hfun(Raster1, ...)
hfun1.add_*
...
hfun2 = Hfun(Raster2, ...)
hfun2.add_*
...
hfun_new = Hfun([hfun1, hfun2], ...)
```
In this case `hfun2` is clipped by bounding box of `hfun1` when calculating the final size function. So if in your case the overlap is such that this becomes useless, then you need to do the clipping manually, by a script along the lines of:
```
hfun1 = Hfun(Raster1, ...)
hfun1.add_*
...
hfun2 = Hfun(Raster2, ...)
hfun2.add_*
...
hfun1_msh = hfun1.msh_t()
hfun1_msh_clip = ocsmesh.utils.clip_mesh_by_shape(hfun1_msh, shape_to_clip_hfun1)
hfun2_msh = hfun2.msh_t()
hfun2_msh_clip = ocsmesh.utils.clip_mesh_by_shape(hfun2_msh, shape_to_clip_hfun2)

index.append(hfun1_msh_clip.tria3['index'])
coord.append(hfun1_msh_clip.vert2['coord'])
value.append(hfun1_msh_clip.value)

index.append(hfun2_msh_clip .tria3['index'] + coord[-1].shape[0])
coord.append(hfun2_msh_clip .vert2['coord'])
value.append(hfun2_msh_clip .value)

composite_hfun = jigsaw_msh_t()
composite_hfun.mshID = 'euclidean-mesh'
composite_hfun.ndims = 2
composite_hfun.crs = hfun1_msh.crs

composite_hfun.vert2 = np.array(
   [(coord, 0) for coord in np.vstack(coord)],
   dtype=jigsaw_msh_t.VERT2_t)
composite_hfun.tria3 = np.array(
   [(index, 0) for index in np.vstack(index)],
   dtype=jigsaw_msh_t.TRIA3_t)
composite_hfun.value = np.array(np.vstack(value), dtype=jigsaw_msh_t.REALS_t)

hfun_new = Hfun(composite_hfun)
```

Here I assumed that `hfun1_msh.crs` and `hfun2_msh.crs` are the same, if not, then the projection code needs to be there too.

Depending on your workflow and specific use-case, I can add helper functions to `utils` so that most of this manual work is taken care of in pieces that makes the workflow customizable. For example right now all the code above (including the projection that is not present here) are actually done in `HfunCollector`, but with certain assumptions about how to clip, etc.

**Comment by TPCollings** [comment]
I can't seem to submit hfun collectors to the `Hfun` function. When I do I get this error: 
![image_720](https://user-images.githubusercontent.com/100429378/231517129-4eadb1c4-2b0c-4fcd-8a2d-bb7fb57134be.png)

I tried clipping the mesh manually using your code and I get a similar error from jigsaw_py:

![image](https://user-images.githubusercontent.com/100429378/231517235-c73463b8-b41c-400e-af39-ce9b9614975e.png)


Any ideas why I might getting these?

**Comment by SorooshMani-NOAA** [comment]
I think the first one is due to this: https://github.com/noaa-ocs-modeling/OCSMesh/issues/68.
Can you get the latest `main` branch (or PyPI release) of OCSMesh and check if you still see this issue?

For the second one I actually made a mistake: 
```diff
-hfun_new = Hfun(composite_hfun)
+hfun_new = Hfun(Mesh(composite_hfun))
```
Sorry about that!

**Comment by TPCollings** [comment]
I've created a new env with the most recent PyPI release, and the second method is now running without an error, but I still get the same error when trying to pass Hfun objects to a new Hfun collector? 
![image](https://user-images.githubusercontent.com/100429378/231741154-b4f87d70-8223-4b81-8b93-2bcd35d2274d.png)

**Comment by TPCollings** [comment]
Trying the second suggestion, I get either get weird overlaps or gaps in mesh. These polygons represent the areas I'm trying to mesh, with the inner polygon being meshed using sub_tidal_flow_limiter to refine the shelf edge. 
![image](https://user-images.githubusercontent.com/100429378/231756187-d4d58c6e-eea9-41da-a379-8fc802be05f0.png)

If I mesh create the two meshes append them together, I get this result, which is just the two meshes on top of each other. 
![image](https://user-images.githubusercontent.com/100429378/231756467-7f8e1ded-eada-4051-abac-a662b0c72640.png)

If I clip the larger mesh by the difference in the two domains, I get gaps as shown below. 
![image](https://user-images.githubusercontent.com/100429378/231756684-cc3d1374-1568-4321-b285-beb44a90606d.png)

Perhaps the best solution to this issue is creating an add_region_constraint, as you initially suggested.

**Comment by SorooshMani-NOAA** [comment]
@TPCollings, I think there's a miscommunication here:
> Trying the second suggestion, ...

Are you referring to my suggestion of combining size functions in https://github.com/noaa-ocs-modeling/OCSMesh/issues/74#issuecomment-1505517234 ? Note that the combined size function itself doesn't need to look like a contiguous mesh, and that's OK. But when you use this size function to generate a mesh you'll get a valid mesh. So in the example script in the comment, you need to use `hfun_new` to generate a new mesh.

Note that this is different from generating two meshes and then combining them. While that's also possible, I don't have a recommended way since it's not possible to fully "fix" the boundary edge and nodes of the mesh in the intersection line so that we get a conformal mesh on the two regions that can seamlessly be combined.

In any case I'll look into the issue of passing multiple size functions to form a new one, and I will add the region constraint as well.

**Comment by SorooshMani-NOAA** [comment]
Can you please call `type(base_hfun1)` and `type(base_hfun2)` and get a snapshot of the results? I don't understand why it fails!

**Comment by TPCollings** [comment]
> you need to use hfun_new to generate a new mesh.

I've been doing that, but only with <hfun_new.msh_t()> I'll try and generate one properly and see if that works.

>Can you please call type(base_hfun1) and type(base_hfun2) and get a snapshot of the results? 

![image](https://user-images.githubusercontent.com/100429378/231789026-1020df67-1834-420d-a121-8efd0a9e4b8f.png)

> In any case I'll look into the issue of passing multiple size functions to form a new one, and I will add the region constraint as well.

Thank you!

**Comment by TPCollings** [comment]
> you need to use hfun_new to generate a new mesh.

Ah! This has worked. Thank you for clarifying!

![image](https://user-images.githubusercontent.com/100429378/231791369-47aa80e9-2bde-4f2b-acbe-0d697189bf25.png)

**Comment by SorooshMani-NOAA** [comment]
> Ah! This has worked. Thank you for clarifying!

That's great, I'm glad that it worked! thanks for the update.

> ![image](https://user-images.githubusercontent.com/77082694/231799058-39b6d039-9f5a-410c-9922-27a6db61a07b.png)

I see what's happening now! The issue is that the original "base" size functions you have are of "collector" type. Originally I didn't really consider collector type as valid type to input into a new collector size function. I don't see any major reasons why that can't work, maybe just performance issues if the user is not careful! I consider it in the future (#76 )

**Comment by TPCollings** [comment]
> The issue is that the original "base" size functions you have are of "collector" type.

What should they be them both to be passed to a new Hfun collector?

**Comment by SorooshMani-NOAA** [comment]
In the current version of OCSMesh, you can get their `msh_t` type output and create a new `HfunMesh` from them, then you can pass those to create a new collector object.
```python
base_meshhfun1 = Hfun(Mesh(base_hfun1.msh_t()))
base_meshhfun2 = Hfun(Mesh(base_hfun2.msh_t()))
new_hfun = Hfun([base_meshhfun1, base_meshhfun2], ...)
```

with that being said, I think in your specific case,  because of how bounding boxes overlap, the manual approach (that worked) might still be the right way to go.

**Update**
The valid types are the ones listed in the error message, either `Raster`, `HfunMesh`, `HfunRaster`, or `BaseMesh` objects.

**Comment by SorooshMani-NOAA** [comment]
@TPCollings I implemented the first version of region based constraint in [`feature/hfun_shapeconstr`](https://github.com/noaa-ocs-modeling/OCSMesh/tree/feature/hfun_shapeconstr) branch. Can you please test it and see if it resolves the issue you had with sizing, when you have the chance? Thanks!

Examples of how to use it are in the test:
https://github.com/noaa-ocs-modeling/OCSMesh/blob/52b8c25e4904618c781da6ae54814046ea366f14/tests/api/hfun.py#L881-L887

Please let me know if you have any questions.

**Comment by TPCollings** [comment]
@SorooshMani-NOAA Sorry for the slow reply, I was away last week until today. 

Thanks for creating the function. I'll look at testing this hopefully this week. 

Cheers,

Tom

**Comment by TPCollings** [comment]
Hi @SorooshMani-NOAA,

I've had a little play, but can't get the function to work. The function runs without error, but the resulting mesh does still have small elements in the polygon I specified around the open boundary. I've attached my code. Am I missing something? Do I need to separately apply the constraints before passing the hfun collector to the Jigsaw driver?

The last image shows the region in grey which should be fixed to 25km mesh size.

![image](https://github.com/noaa-ocs-modeling/OCSMesh/assets/100429378/41388131-854d-4d75-a23f-7d2df5bc999b)

![image](https://github.com/noaa-ocs-modeling/OCSMesh/assets/100429378/bf2f0bfc-68fb-4c80-b40d-bd475c3c63ac)

![image](https://github.com/noaa-ocs-modeling/OCSMesh/assets/100429378/87953e31-348e-4711-bbaf-50a56cd9e602)

**Comment by SorooshMani-NOAA** [comment]
@TPCollings, thank you for testing. I think I didn't really test for the `'fast'` collector size function, let me check and see if that's the problem. In the meantime can you please try using `'exact'` collector size function to see if it makes any difference?

Also if you don't mind, can you extract the size function and save it as a mesh to see if it at least looks right or not? To do so after applying all the sizes and constraints do the following
```python
Mesh(base_hfun.msh_t()).write('/path/to/output/file.2dm', format='2dm', overwrite=True)
```

Thanks!

**Comment by SorooshMani-NOAA** [comment]
@TPCollings I can confirm that this is an issue with `fast` method of collector size function. I'll try to fix, but I believe if you use `exact` method it should work as intended.

**Comment by SorooshMani-NOAA** [comment]
@TPCollings I added a fix for `fast` collector as well. You can also try it again with the latest in this branch. Thanks!

**Comment by TPCollings** [comment]
@SorooshMani-NOAA When I try and run the script using 'exact' the script hangs when trying to pass the mesh to the Jigsaw driver. I left it running overnight at after 15 hours it was still running. I'm trying again this morning but it looks like the issue is the same.

 I'll try again with the new patch using a fast collector and see if that works instead.

**Comment by SorooshMani-NOAA** [comment]
Sorry for the long runtime and thanks for testing. May I ask how many DEMs you used that is taking more than 15 hours to compute? I'd also appreciate it if you could let me know what and how much is the CPU and RAM of the machine you're using.

Anyhow, the `fast` method was implemented for exactly this scenario. I originally used it as a hack, but then realized this hack might be useful to others too! The downside is that the extracted features from DEMs won't be as exact.

**Comment by TPCollings** [comment]
It's just single DEM that's been pieced together and resample to the highest resolution data (90m). The DEM is about 600MB, so not massive. I'm using a powerful virtual machine, with 96 CPU and 196GB of RAM. I'm now testing the fast method but it is also taking a while. Currently on ~70 minutes trying to pass the mesh to the Jigsaw driver. I think I can see the process in the system monitor and it's currently using 44GB of RAM. 

Would you expect this function to be this computationally expensive? Or is it more likely that there is a problem with how I'm implementing the code? I'm trying to use quite a complicated polygon for the region to be constrained. Could that be causing an issue?

Cheers

**Comment by SorooshMani-NOAA** [comment]
Interesting! If the script goes through quickly without the shape/region constraint, and based on the numbers you gave me, I believe the issue should be just the complexity of the polygon. In the current implementation of the shape-constraint I do a basic `points.within(input_shape)` call which could be slow if the shape is too complex. In the implementation my assumption was that for size function, basic polygons could be enough to constrain the sizes. If it is possible, maybe try a simpler shape and see how it works.

Thanks

**Comment by SorooshMani-NOAA** [comment]
@TPCollings I'm going to go ahead and merge the changes related to this feature. If you're still testing/interested in using it, and are facing issues (performance, wrong results, etc.) please create a separate ticket to follow up. Thank you!
